//! Compile `proto/vector_tile.proto` and write prost-derived Rust types to
//! `src/convert/mvt/vector_tile.rs` so the generated code can be checked in.
//!
//! Uses `protox` (pure-Rust protobuf compiler) to avoid needing the `protoc`
//! binary at codegen time.

use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

const HEADER: &str = "//! Prost-derived Rust types for the MVT (Mapbox Vector Tile) wire format.
//!
//! Regenerated from `proto-codegen/proto/vector_tile.proto` by
//! `just rust::gen-mvt-proto`. Do not edit by hand - CI's `autofix.ci`
//! workflow regenerates and commits this file when the .proto changes.
#![allow(
    clippy::doc_markdown,
    clippy::struct_field_names,
    clippy::pedantic,
    reason = \"generated by prost-build from vector_tile.proto\"
)]

";

fn main() {
    // The codegen crate lives at `mlt-core/proto-codegen`; resolve paths
    // relative to its `CARGO_MANIFEST_DIR` so the script works whether invoked
    // from the workspace root, the `rust/` dir, or the codegen dir itself.
    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let mlt_core = manifest_dir.parent().expect("crate has parent");
    let proto_dir = manifest_dir.join("proto");
    let proto = proto_dir.join("vector_tile.proto");
    let out_path = mlt_core.join("src/convert/mvt/vector_tile.rs");

    let fds =
        protox::compile([&proto], [&proto_dir]).expect("compile vector_tile.proto with protox");

    let tmp_dir = tempdir();
    prost_build::Config::new()
        .out_dir(&tmp_dir)
        .compile_fds(fds)
        .expect("prost-build code generation");

    let body = fs::read_to_string(tmp_dir.join("vector_tile.rs")).expect("read prost-build output");
    fs::write(&out_path, format!("{HEADER}{body}")).expect("write generated file");

    fs::remove_dir_all(&tmp_dir).ok();

    // Apply project rustfmt so the file passes `cargo fmt --check`.
    let status = Command::new("rustfmt")
        .arg("--edition=2024")
        .arg(&out_path)
        .status()
        .expect("invoke rustfmt");
    assert!(status.success(), "rustfmt failed");

    println!("wrote {}", out_path.display());
}

fn tempdir() -> PathBuf {
    let mut path = env::temp_dir();
    path.push(format!("mlt-mvt-proto-codegen-{}", std::process::id()));
    fs::create_dir_all(&path).expect("create temp dir");
    path
}
