#!/bin/bash
set -euo pipefail

CURRENT_DIR=$(pwd)

export CXXFLAGS="-g -std=c++17 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -O3"

if [[ $(uname -s) == "Darwin" ]]; then
    echo "Detected macOS"
    export CXXFLAGS="${CXXFLAGS} -arch arm64 -arch x86_64"
    ls /Library/Java/JavaVirtualMachines/ || true
    find / -name '*temurin*'
    ls /usr/lib/jvm/ || true
    ls /usr/lib/jvm/temurin-17-jdk-amd64/ || true
    export JNI_INCLUDE="/Library/Java/JavaVirtualMachines/microsoft-17.jdk/Contents/Home"
    export JNI_PLATFORM="darwin"
    export LINKFLAGS="-bundle"
elif [[ $(uname -s) == "Linux" ]]; then
    echo "Detected Linux"
    export JNI_INCLUDE="/usr/lib/jvm/temurin-17-jdk-amd64"
    export JNI_PLATFORM="linux"
    export LINKFLAGS="-shared"
else
    echo "Detected Windows"
    export JNI_INCLUDE="C:/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk/17.0.11-9/x64"
    export JNI_PLATFORM="win32"
    export LINKFLAGS="-shared"
fi

if [[ ! -f build/libfsst.a ]]; then
    mkdir -p ${CURRENT_DIR}/build
    cd ${CURRENT_DIR}/build
    if [[ ! -d springmeyer-fsst-afd69ed ]]; then
        curl -L https://github.com/springmeyer/fsst/tarball/afd69ed -o fsst.tar.gz
        tar -xvf fsst.tar.gz
    fi
    cd ${CURRENT_DIR}/build/springmeyer-fsst-afd69ed/
    echo "Building fsst in $(pwd)"
    cp ${CURRENT_DIR}/resources/Makefile .
    make
    cp libfsst.a ${CURRENT_DIR}/build/
    cp fsst.h ${CURRENT_DIR}/build/
fi

cd ${CURRENT_DIR}

# -Wl,-rpath,'$ORIGIN' is used to set the rpath to the current directory
MODULE_BUILD="c++ ${CXXFLAGS} -I${JNI_INCLUDE}/include -I${JNI_INCLUDE}/include/${JNI_PLATFORM} -I./build -I./resources ./resources/FsstWrapper.cpp ./build/libfsst.a ${LINKFLAGS} -o ./build/FsstWrapper.so"
echo "Building FsstWrapper.so"
echo ${MODULE_BUILD}
${MODULE_BUILD}
