/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FsstWrapper */

#ifndef _Included_FsstWrapper
#define _Included_FsstWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FsstWrapper
 * Method:    compress
 * Signature: ([B)LSymbolTable;
 */
JNIEXPORT jobject JNICALL Java_com_fsst_FsstEncoder_compress
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
