#!/bin/bash
set -euo pipefail

if [[ -f resources/build/FsstWrapper.so ]]; then
    echo "FsstWrapper.so exists, skipping compilation"
    echo "  Remove ./resources/build/FsstWrapper.so to recompile"
else
    echo "FsstWrapper.so does not exist, building now"
    mkdir -p resources/build
    cd resources/build
    cmake .. -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_BUILD_TYPE=Release
    cmake --build .
fi
echo "Compilation successful"
