#!/bin/bash
set -euo pipefail

if [[ -f build/FsstWrapper.so ]]; then
    echo "FsstWrapper.so exists, skipping compilation"
    echo "  Remove ./build/FsstWrapper.so to recompile"
    echo "  Remove ./build to reconfigure & compiled"
else
    echo "FsstWrapper.so does not exist, building now"
    mkdir -p resources/build
    cd resources/build
    cmake .. -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_BUILD_TYPE=Release
    cmake --build .
    cp -f FsstWrapper.so ../../build/FsstWrapper.so
fi
echo "Compilation successful"
