/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FsstWrapper */

#ifndef _Included_FsstWrapper
#define _Included_FsstWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FsstWrapper
 * Method:    compress
 * Signature: ([B)LSymbolTable;
 */

extern "C"
JNIEXPORT jobject JNICALL
Java_org_maplibre_mlt_converter_encodings_fsst_FsstJni_compress(JNIEnv*, jclass,
                                                       jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
