name: rerun
description: Reruns the selected workflow

inputs:
  run_id:
    description: 'Contents of the github.run_id variable'
    required: true
runs:
  using: "composite"
  steps:
    - name: rerun ${{ inputs.run_id }}
      env:
        GH_REPO: ${{ github.repository }}
        GH_TOKEN: ${{ github.token }}
        GH_DEBUG: api
      run: |
        gh run watch ${{ inputs.run_id }} > /dev/null 2>&1
        gh run rerun ${{ inputs.run_id }} --failed
      shell: bash
