#include "synthetic_mlt_generator.hpp"

#include <gtest/gtest.h>

#include <algorithm>
#include <mlt/coordinate.hpp>
#include <mlt/decoder.hpp>
#include <mlt/geometry.hpp>
#include <mlt/metadata/tileset.hpp>

#include <filesystem>
#include <fstream>

using namespace mlt::test;

namespace {

/// Allow the tests to be run from a variety of working directories within the workspace
const std::string basePath = []() {
    std::string basePath = "test/synthetic/0x01/";
    for (int i = 0; i < 3; ++i) {
        if (std::filesystem::exists(basePath)) {
            return basePath;
        }
        basePath.insert(0, "../");
    }
    throw std::runtime_error("Fixture base path not found");
}();

/// Loads the contents of a binary file into a vector of bytes
std::vector<uint8_t> readBinaryFile(const std::string& filePath) {
    std::ifstream file(filePath, std::ios::binary);
    if (file.is_open()) {
        return std::vector<uint8_t>((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
    } else {
        throw std::runtime_error("Unable to open file: " + filePath);
    }
}

/// Compare a generated tile against a file
void checkSynthetic(const SyntheticMltGenerator::GeneratedTile& generated) {
    const auto filePath = basePath + generated.name + ".mlt";
    const auto fileContents = readBinaryFile(filePath);
    EXPECT_EQ(fileContents, generated.bytes);
}

/// Compare a collection of generated tiles against fixture files
void checkSynthetic(const SyntheticMltGenerator::GeneratedTiles& generatedTiles) {
    for (const auto& generated : generatedTiles) {
        checkSynthetic(generated);
    }
}

/// Compare a single tile from a collection
void checkSyntheticByName(const SyntheticMltGenerator::GeneratedTiles& generatedTiles, const std::string& name) {
    SCOPED_TRACE("Checking synthetic tile: " + name);
    const auto it = std::ranges::find_if(generatedTiles, [&](const auto& t) { return t.name == name; });
    ASSERT_NE(it, generatedTiles.end()) << "Generated tile not found: " << name;
    checkSynthetic(*it);
}

TEST(SyntheticMltGenerator, GeneratePoints) {
    checkSynthetic(SyntheticMltGenerator::generatePoints());
}

TEST(SyntheticMltGenerator, GenerateLine) {
    checkSynthetic(SyntheticMltGenerator::generateLine());
}

TEST(SyntheticMltGenerator, GenerateLines) {
    checkSynthetic(SyntheticMltGenerator::generateLines());
}

TEST(SyntheticMltGenerator, GeneratePolyHole) {
    checkSynthetic(SyntheticMltGenerator::generatePolyHole());
}

TEST(SyntheticMltGenerator, GeneratePolygons) {
    checkSynthetic(SyntheticMltGenerator::generatePolygons());
}

TEST(SyntheticMltGenerator, GenerateMultiPoint) {
    checkSynthetic(SyntheticMltGenerator::generateMultiPoint());
}

TEST(SyntheticMltGenerator, GenerateMultiPoints) {
    checkSynthetic(SyntheticMltGenerator::generateMultiPoints());
}

TEST(SyntheticMltGenerator, GenerateMultiLine) {
    checkSynthetic(SyntheticMltGenerator::generateMultiLine());
}

TEST(SyntheticMltGenerator, GenerateMultiLineStrings) {
    checkSynthetic(SyntheticMltGenerator::generateMultiLineStrings());
}

TEST(SyntheticMltGenerator, GenerateExtent4096) {
    checkSynthetic(SyntheticMltGenerator::generateExtent4096());
}

TEST(SyntheticMltGenerator, GenerateExtent) {
    checkSynthetic(SyntheticMltGenerator::generateExtent());
}

// Why doesn't this work?
TEST(SyntheticMltGenerator, DISABLED_GenerateExtentLarge) {
    checkSynthetic(SyntheticMltGenerator::generateExtent(1073741824U));
}

TEST(SyntheticMltGenerator, GenerateIds) {
    checkSynthetic(SyntheticMltGenerator::generateIds());
}

TEST(SyntheticMltGenerator, GenerateIdsCollection) {
    checkSynthetic(SyntheticMltGenerator::generateIdsCollection());
}

// Currently not working because Java generates a nullable column and we don't.
// I think that's effectively a bug on the Java side because the column contains no nulls.
TEST(SyntheticMltGenerator, DISABLED_GeneratePropU64) {
    checkSynthetic(SyntheticMltGenerator::generatePropU64());
}

TEST(SyntheticMltGenerator, DISABLED_GenerateProperties) {
    checkSynthetic(SyntheticMltGenerator::generateProperties());
}

TEST(SyntheticMltGenerator, GenerateMixPtLine) {
    checkSynthetic(SyntheticMltGenerator::generateMixPtLine());
}

TEST(SyntheticMltGenerator, GenerateMixed) {
    // This test verifies that all mix fixture files can be loaded and the test helper works correctly.
    // The actual fixture files were generated by the Java SyntheticMltGenerator.generateMixed() and
    // generateMixedCombine() methods, which create 182+ mix combinations.
    int mixFileCount = 0;
    std::error_code ec;
    for (const auto& entry : std::filesystem::directory_iterator(basePath, ec)) {
        if (!ec && entry.path().extension() == ".mlt") {
            auto filename = entry.path().filename().string();
            if (filename.starts_with("mix_")) {
                mixFileCount++;
            }
        }
    }

    // Java generateMixed() creates multiple combinations (2-combinations through 7-combinations,
    // plus A-A and A-B-A variants) from 7 geometry types, resulting in ~182 fixture files
    EXPECT_GT(mixFileCount, 100) << "Expected many mix fixture files to be generated by Java";
}

/// Parameterized test for validating all mix fixture files
class MixFixtureTest : public ::testing::TestWithParam<std::string> {
public:
    static std::vector<std::string> discoverMixFixtures() {
        std::vector<std::string> result;
        std::error_code ec;
        if (std::filesystem::exists(basePath)) {
            for (const auto& entry : std::filesystem::directory_iterator(basePath, ec)) {
                if (!ec && entry.path().extension() == ".mlt") {
                    auto filename = entry.path().filename().string();
                    if (filename.starts_with("mix_")) {
                        result.push_back(filename.substr(0, filename.length() - 4)); // Remove .mlt
                    }
                }
            }
        }
        std::ranges::sort(result);
        return result;
    }
};

TEST_P(MixFixtureTest, CanLoadFixtureFile) {
    // This test validates that all mix fixture files generated by Java exist and can be loaded.
    // The Java SyntheticMltGenerator.generateMixed() and generateMixedCombine() methods create
    // these files by combining the 7 geometry types (pt, line, poly, polyh, mpt, mline, mpoly)
    // in various combinations: 2-combinations, 3-combinations, etc., plus A-A and A-B-A variants.
    const auto mixTileName = GetParam();
    const auto filePath = basePath + mixTileName + ".mlt";

    // Load the fixture file
    std::ifstream file(filePath, std::ios::binary);
    ASSERT_TRUE(file.is_open()) << "Could not open fixture file: " << filePath;

    std::vector<uint8_t> fileContents((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
    file.close();

    // Verify file has content
    ASSERT_GT(fileContents.size(), 0) << "Fixture file is empty: " << filePath;
}

INSTANTIATE_TEST_SUITE_P(MixGeometryFixtures,
                         MixFixtureTest,
                         ::testing::ValuesIn(MixFixtureTest::discoverMixFixtures()),
                         [](const ::testing::TestParamInfo<std::string>& info) { return info.param; });

/// Individual tests for specific mix combinations (representative samples)
TEST(SyntheticMltGenerator, GenerateMixedMix2PtLine) {
    checkSyntheticByName(SyntheticMltGenerator::generateMixed(), "mix_2_pt_line");
}

TEST(SyntheticMltGenerator, GenerateMixedMix2PtPt) {
    checkSyntheticByName(SyntheticMltGenerator::generateMixed(), "mix_2_pt_pt");
}

TEST(SyntheticMltGenerator, GenerateSharedDictNoSharedDict) {
    checkSyntheticByName(SyntheticMltGenerator::generateSharedDictionaries(), "props_no_shared_dict");
}

TEST(SyntheticMltGenerator, GenerateSharedDictBasic) {
    checkSyntheticByName(SyntheticMltGenerator::generateSharedDictionaries(), "props_shared_dict");
}

TEST(SyntheticMltGenerator, GenerateSharedDictNoStructName) {
    checkSyntheticByName(SyntheticMltGenerator::generateSharedDictionaries(), "props_shared_dict_no_struct_name");
}

TEST(SyntheticMltGenerator, GenerateSharedDictNoChildName) {
    checkSyntheticByName(SyntheticMltGenerator::generateSharedDictionaries(), "props_shared_dict_no_child_name");
}

// TODO: These cases still fail

TEST(SyntheticMltGenerator, DISABLED_GenerateSharedDictOneChild) {
    checkSyntheticByName(SyntheticMltGenerator::generateSharedDictionaries(), "props_shared_dict_one_child");
}

TEST(SyntheticMltGenerator, DISABLED_GenerateSharedDictTwoSamePrefix) {
    checkSyntheticByName(SyntheticMltGenerator::generateSharedDictionaries(), "props_shared_dict_2_same_prefix");
}

/// FSST string encoding is non-deterministic due to symbol selection heuristics.
/// We rely on round-trip testing for these.
TEST(SyntheticMltGenerator, DISABLED_GeneratePropsStrFsst) {
    checkSynthetic(SyntheticMltGenerator::generatePropsStrFsst());
}
TEST(SyntheticMltGenerator, DISABLED_GenerateSharedDictBasicFsst) {
    checkSyntheticByName(SyntheticMltGenerator::generateSharedDictionaries(), "props_shared_dict_fsst");
}
TEST(SyntheticMltGenerator, DISABLED_GenerateSharedDictOneChildFsst) {
    checkSyntheticByName(SyntheticMltGenerator::generateSharedDictionaries(), "props_shared_dict_one_child_fsst");
}
TEST(SyntheticMltGenerator, DISABLED_GenerateSharedDictNoStructNameFsst) {
    checkSyntheticByName(SyntheticMltGenerator::generateSharedDictionaries(), "props_shared_dict_no_struct_name_fsst");
}
TEST(SyntheticMltGenerator, DISABLED_GenerateSharedDictNoChildNameFsst) {
    checkSyntheticByName(SyntheticMltGenerator::generateSharedDictionaries(), "props_shared_dict_no_child_name_fsst");
}

} // namespace
