name: Publish docs

on:
  workflow_call:
  workflow_dispatch:

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: taiki-e/install-action@6a1bd70eaac3c8bdf093356838d7ee09fda951cf # v2.85.5
        with: { tool: 'just,cargo-binstall' }

      - name: Build MLT documentation
        run: just -v docs-build

      - name: Deploy 🚀
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main' && github.repository_owner == 'maplibre'
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with: { branch: gh-pages, folder: site }

      - run: just -v assert-git-is-clean
