name: Java - Release

on:
  push:
    tags:
      - 'java-v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up JDK
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: taiki-e/install-action@4684b8405694ae9dd42c9f39ba901a70ae83f4a3 # v2.82.9
        with: { tool: 'just,cargo-binstall' }

      - name: Get version from tag
        id: get_version
        run: |
          version="$(just ci-extract-version java ${{ github.ref_name }})"
          echo version="$version" >> "$GITHUB_ENV"

      - name: Make gradlew executable
        run: chmod +x ./java/gradlew

      - name: Publish to Maven Central
        working-directory: java
        run: ./gradlew publishToMavenCentral -Pversion=${{ env.version }}
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

      - name: Build CLI tool
        working-directory: java
        run: ./gradlew cli
      - run: just -v assert-git-is-clean

      - name: Rename CLI artifacts
        run: |
          cp java/mlt-cli/build/libs/encode.jar mlt-encode.jar
          cp java/mlt-cli/build/libs/decode.jar mlt-decode.jar

      - name: Add CLI artifacts to GitHub release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        with:
          tag_name: java-v${{ env.version }}
          fail_on_unmatched_files: true
          name: java-v${{ env.version }}
          files: |
            mlt-encode.jar
            mlt-decode.jar
