name: TypeScript CI

on:
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: taiki-e/install-action@9bcaee1dcae34154180f412e2fa69355a7cda9f6 # v2.82.6
        with: { tool: 'just,cargo-binstall' }
      - uses: ./.github/actions/mlt-setup-node
      - name: Lint JS code. If fails, run `just ts::fmt` to reformat, and `just ts::lint` to see issues locally
        run: just -v ts::lint
      - run: just -v ts::test
      - run: just -v ts::build
      - name: Codecov upload
        if: "github.repository_owner == 'maplibre' && !cancelled()"
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: ts/coverage/coverage-final.json
      - run: just -v assert-git-is-clean
